In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python yang digunakan untuk komputasi matriks.
Matplotlib merupakan library python yang digunakan untuk presentasi data berupa grafik/plot.
. . . . .

In [34]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [35]:
print(x)

[['Adi' 30 72000.0]
 ['Budi' 20 48000.0]
 ['Cantika' 35 45000.0]
 ['Budi' 25 61000.0]
 ['Cantika' 20 nan]
 ['Adi' 30 58000.0]
 ['Budi' 25 52000.0]
 ['Adi' 35 79000.0]
 ['Cantika' 40 83000.0]
 ['Adi' 20 67000.0]]


In [36]:
print(y)

['No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes']


In [37]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [38]:
print(x)

[['Adi' 30.0 72000.0]
 ['Budi' 20.0 48000.0]
 ['Cantika' 35.0 45000.0]
 ['Budi' 25.0 61000.0]
 ['Cantika' 20.0 62777.77777777778]
 ['Adi' 30.0 58000.0]
 ['Budi' 25.0 52000.0]
 ['Adi' 35.0 79000.0]
 ['Cantika' 40.0 83000.0]
 ['Adi' 20.0 67000.0]]


In [40]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [41]:
print(x)

[[1.0 0.0 0.0 30.0 72000.0]
 [0.0 1.0 0.0 20.0 48000.0]
 [0.0 0.0 1.0 35.0 45000.0]
 [0.0 1.0 0.0 25.0 61000.0]
 [0.0 0.0 1.0 20.0 62777.77777777778]
 [1.0 0.0 0.0 30.0 58000.0]
 [0.0 1.0 0.0 25.0 52000.0]
 [1.0 0.0 0.0 35.0 79000.0]
 [0.0 0.0 1.0 40.0 83000.0]
 [1.0 0.0 0.0 20.0 67000.0]]


In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [43]:
print(y)

[0 0 1 0 0 1 1 1 0 1]


In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [45]:
print(x_train)

[[0.0 1.0 0.0 25.0 52000.0]
 [0.0 0.0 1.0 20.0 62777.77777777778]
 [1.0 0.0 0.0 30.0 72000.0]
 [0.0 1.0 0.0 25.0 61000.0]
 [0.0 1.0 0.0 20.0 48000.0]
 [1.0 0.0 0.0 35.0 79000.0]
 [0.0 0.0 1.0 40.0 83000.0]
 [1.0 0.0 0.0 30.0 58000.0]]


In [46]:
print(x_test)

[[0.0 0.0 1.0 35.0 45000.0]
 [1.0 0.0 0.0 20.0 67000.0]]


In [47]:
print(y_train)

[1 0 0 0 0 1 0 1]


In [48]:
print(y_test)

[1 1]


In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [51]:
print(x_train)

[[0.0 1.0 0.0 -0.4745789978762495 -1.0662015647686784]
 [0.0 0.0 1.0 -1.2339053944782488 -0.14485143752981997]
 [1.0 0.0 0.0 0.2847473987257497 0.6435203208292029]
 [0.0 1.0 0.0 -0.4745789978762495 -0.2968267162496319]
 [0.0 1.0 0.0 -1.2339053944782488 -1.4081459418882547]
 [1.0 0.0 0.0 1.044073795327749 1.2419229807884613]
 [0.0 0.0 1.0 1.8034001919297482 1.5838673579080376]
 [1.0 0.0 0.0 0.2847473987257497 -0.5532849990893142]]


In [52]:
print(x_test)

[[0.0 0.0 1.0 1.044073795327749 -1.6646042247279371]
 [1.0 0.0 0.0 -1.2339053944782488 0.2160898494297325]]
